# nginx-scaled.conf - Digunakan setelah horizontal scaling (app-node-3 ditambahkan)
worker_processes auto;
error_log /var/log/nginx/error.log warn;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format cloud_log '$remote_addr - [$time_local] "$request" $status '
                         'upstream: $upstream_addr cache: $upstream_cache_status';
    access_log /var/log/nginx/access.log cloud_log;

    # =============================================
    # UPSTREAM GROUP SETELAH SCALING
    # Sekarang ada 3 node (horizontal scale-out)
    # =============================================
    upstream app_servers {
        server app-node-1:5000 weight=1 max_fails=3 fail_timeout=10s;
        server app-node-2:5000 weight=1 max_fails=3 fail_timeout=10s;
        server app-node-3:5000 weight=1 max_fails=3 fail_timeout=10s;  # NODE BARU!
        keepalive 32;
    }

    proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=cloud_cache:10m
                     max_size=100m inactive=60m use_temp_path=off;

    server {
        listen 80;
        server_name localhost;

        add_header X-Load-Balancer "nginx-cloud-lb-scaled";
        add_header X-Active-Nodes "3";

        location / {
            proxy_pass http://app_servers;
            proxy_cache cloud_cache;
            proxy_cache_valid 200 30s;
            proxy_cache_use_stale error timeout updating;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            add_header X-Cache-Status $upstream_cache_status;
            add_header X-Served-By $upstream_addr;
            proxy_next_upstream error timeout http_500 http_502 http_503;
            proxy_next_upstream_tries 3;
        }

        location /health {
            proxy_pass http://app_servers;
            proxy_cache off;
        }

        location /static/ {
            proxy_pass http://app_servers;
            proxy_cache cloud_cache;
            proxy_cache_valid 200 5m;
            add_header X-Cache-Status $upstream_cache_status;
        }

        location /no-cache {
            proxy_pass http://app_servers;
            proxy_cache off;
            add_header X-Served-By $upstream_addr;
        }
    }

    server {
        listen 8080;
        location /nginx_status { stub_status on; allow all; }
    }
}
